#!/usr/bin/env python

import os
import sys
import json
import time
from os.path import expanduser

if 2 > len(sys.argv):
    print("Usage: getInstances [-v] [-u]  <Machine Name> [Json Filename]")
    exit(-1)

verbose = False
forceUpdate = False
argv = sys.argv
if '-v' in sys.argv:
    verbose = True
    argv = [ arg for arg in argv if '-v' != arg ]

if '-u' in sys.argv:
    forceUpdate = True
    argv = [ arg for arg in argv if '-u' != arg ]

name = argv[1]
filename = '/%s/Instances.json' % expanduser("~")
if 3 == len(argv):
    data = json.load(open(argv[2]))
elif os.path.exists(filename) and ( os.stat(filename).st_mtime + 3600 > time.time() ) and (os.stat(filename).st_size > 0) and not forceUpdate:
    print "%s size: %d" % (filename, os.stat(filename).st_size)
    data = json.load(open(filename))
else:
    os.system('with-aws bbc-production aws ec2 describe-instances > %s' % filename)
    data = json.load(open(filename))


found=False
fuzzy=True # always set to true. Leaving it as a var just in case I want to configure it
for resv in data['Reservations']:
    for inst in resv['Instances']:
        if 'running' == inst['State']['Name']:
            for tag in inst['Tags']:
                #print json.dumps(tag, indent=4, sort_keys=True)
                if ('Name' == tag['Key']) or ('aws:cloudformation:stack-name' == tag['Key']):
                    if ( name == tag['Value']) or ( fuzzy and name in tag['Value']):
                        found=True
                        if verbose:
                            print "%s\t%s\t%s\t%s\t%s" % (inst['PrivateIpAddress'], tag['Value'], inst['LaunchTime'], inst['InstanceId'], inst['ImageId'])
                        else:
                            print inst['PrivateIpAddress']
                        break
                #else if ():
            if found:
                #print inst['PrivateIpAddress']
                found=False
